### ISSUE TITLE
AirServer download failing

### ISSUE THREAD

**Issue by eshirk** [autopkg/sheagcraig-recipes#47]
Getting the following error: "Error in local.munki.AirServer: Processor: AirServerURLProvider: Error: Couldn't find AirServer download URL in http://www.airserver.com/Download/MacPC"

http://www.airserver.com/Download/MacPC itself loads fine.

**Comment by dcoobs** [comment]
It looks like AirServer folks added a hyphen to their version number in the download URL:

    http://dl.airserver.com/mac/AirServer-7.2.0-2.dmg
instead of

    http://dl.airserver.com/mac/AirServer-7.2.0.dmg

I was able to modify the following line in **[AirServerURLProvider.py](https://github.com/autopkg/sheagcraig-recipes/blob/master/AirServer/AirServerURLProvider.py)** to get things working:

    re_dmg_link = re.compile(r'href="(?P<url>http://dl.airserver.com/mac/AirServer-[\d.]+-[\d.]+.dmg)”’)

However, I wonder if this is a permanent change or a one-time issue due to a re-release or something of that nature? We'll probably have to wait until the next release to find out.

**Comment by sheagcraig** [comment]
Cool-thanks for the detective work @dcoobs. So here's what I would say:
Go ahead and fork the repo, make the change, and do a PR for me. And then I'll pull the trigger on it for now, but if they go back to the old scheme we can go back.

And actually, we could make the trailing "-\d" optional:
`re_dmg_link = re.compile(r'href="(?P<url>http://dl.airserver.com/mac/AirServer-[\d.]+-*\d*.dmg)”’)`
or maybe 
`re_dmg_link = re.compile(r'href="(?P<url>http://dl.airserver.com/mac/AirServer-[\d.]+(-\d*)+.dmg)”’)`
Definitely try them before you by them! Just typing it out off the top of my head.

**Comment by dcoobs** [comment]
@sheagcraig PR created. Both of your regex appeared to work so I just went with the second one.

**Comment by macmule** [comment]
also added a PR :)

**Comment by WardsParadox** [comment]
Why not throw another cookie in the cookie Jar :)
